
CREATE TABLE KAKAO_RM
(
    ROOM_ID VARCHAR(20)
    ,PRIMARY KEY(ROMM_ID)
);

CREATE TABLE KAKAO_RM_USER
(
    ROOM_ID VARCHAR(20)
    ,USER_ID VARCHAR(20)
    ,PRIMARY KEY(ROMM_ID, USER_ID)
);

CREATE TABLE KAKAO_SPRAY
(
    ROOM_ID VARCHAR(20)
    ,USER_ID VARCHAR(20)
    ,TOKEN VARCHAR(3)
    ,YEARMONTH BIGINT
    ,TOTAL_MONEY BIGINT
    ,CREATEDATE DATETIME
    ,PRIMARY KEY(ROOM_ID, USER_ID, TOKEN, YEARMONTH)
) PARTITION BY RANGE (YEARMONTH) (PARTITION p0 VALUES LESS THAN (202010),
                                  PARTITION p1 VALUES LESS THAN (202011),
                                  PARTITION p2 VALUES LESS THAN (202012),
                                  PARTITION p3 VALUES LESS THAN (202101),
                                  PARTITION p4 VALUES LESS THAN (202102),
                                  PARTITION p5 VALUES LESS THAN MAXVALUE);

CREATE TABLE KAKAO_DETAIL
(
    ROOM_ID VARCHAR(20)
    ,USER_ID VARCHAR(20)
    ,TOKEN VARCHAR(3)
    ,YEARMONTH BIGINT
    ,SEQ BIGINT NOT NULL
    ,SPRAY_MONEY BIGINT NOT NULL
    ,PRIMARY KEY(ROOM_ID, USER_ID, TOKEN, YEARMONTH, SEQ)   
) PARTITION BY RANGE (YEARMONTH) (PARTITION p0 VALUES LESS THAN (202010),
                                  PARTITION p1 VALUES LESS THAN (202011),
                                  PARTITION p2 VALUES LESS THAN (202012),
                                  PARTITION p3 VALUES LESS THAN (202101),
                                  PARTITION p4 VALUES LESS THAN (202102),
                                  PARTITION p5 VALUES LESS THAN MAXVALUE);

CREATE TABLE KAKAO_REC_DETAIL
(
    ROOM_ID VARCHAR(20)
    ,USER_ID VARCHAR(20)
    ,TOKEN VARCHAR(3)
    ,YEARMONTH BIGINT
    ,SEQ BIGINT
    ,REC_USER_ID VARCHAR(20)
    ,PRIMARY KEY(ROOM_ID, USER_ID, TOKEN, YEARMONTH, SEQ)     
) PARTITION BY RANGE (YEARMONTH) (PARTITION p0 VALUES LESS THAN (202010),
                                  PARTITION p1 VALUES LESS THAN (202011),
                                  PARTITION p2 VALUES LESS THAN (202012),
                                  PARTITION p3 VALUES LESS THAN (202101),
                                  PARTITION p4 VALUES LESS THAN (202102),
                                  PARTITION p5 VALUES LESS THAN MAXVALUE);